
add_library_ex(CommonDataModel
  H_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/CommonDataModel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/Doxy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/Macros.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PhysiologyEngine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/stdafx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitCalculator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitNode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitPath.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuitCalculator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuitNode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuitPath.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuitCalculator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuitNode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuitPath.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuitCalculator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuitNode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuitPath.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentGraph.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentLink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentNodes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentTransportGraph.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEFluidCompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEFluidCompartmentLink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEGasCompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEGasCompartmentGraph.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEGasCompartmentLink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SELiquidCompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SELiquidCompartmentGraph.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SELiquidCompartmentLink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/substances/SEGasSubstanceQuantity.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/substances/SELiquidSubstanceQuantity.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/substances/SESubstanceQuantity.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/thermal/SEThermalCompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/thermal/SEThermalCompartmentLink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/tissue/SETissueCompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEActionManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAdvanceHandler.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAdvanceTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAnesthesiaMachineActionCollection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAutoSerialization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SECondition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEConditionManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDataRequest.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDataRequestManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDecimalFormat.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilizationEngineConvergence.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilizationLedger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilizationPropertyConvergence.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEngineConfiguration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEngineStabilization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEngineTracker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEnvironmentActionCollection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEventManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEInhalerActionCollection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEPatientActionCollection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEPatientConfiguration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SESerializeState.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SETimedStabilization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBActions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBAnesthesiaMachine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBAnesthesiaMachineActions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBCircuit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBCompartment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBConditions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBElectroCardioGram.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEngine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironmentActions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironmentConditions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEvents.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBInhaler.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBInhalerActions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatient.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientActions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientAssessments.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientConditions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientNutrition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPhysiology.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBProperties.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBScenario.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBSubstance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBSubstanceQuantity.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBTestReport.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/SEMeal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/SENutrition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/SEPatient.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAcuteRespiratoryDistressSyndromeExacerbation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAcuteStress.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAirwayObstruction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAsthmaAttack.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEBrainInjury.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEBronchoconstriction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SECardiacArrest.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestCompression.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestCompressionForce.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestCompressionForceScale.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestOcclusiveDressing.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChronicObstructivePulmonaryDiseaseExacerbation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEConsciousRespiration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEConsciousRespirationCommand.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEConsumeNutrients.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEDyspnea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEExercise.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEForcedExhale.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEForcedInhale.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEForcedPause.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEHemorrhage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEIntubation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SELobarPneumoniaExacerbation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEMechanicalVentilation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SENeedleDecompression.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEPatientAction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEPatientAssessmentRequest.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEPericardialEffusion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SERespiratoryFatigue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceAdministration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceBolus.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceCompoundInfusion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceInfusion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESupplementalOxygen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SETensionPneumothorax.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEUrinate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEUseInhaler.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SECompleteBloodCount.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEComprehensiveMetabolicPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEPatientAssessment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEPulmonaryFunctionTest.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEUrinalysis.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEUrinalysisMicroscopic.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEAcuteRespiratoryDistressSyndrome.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicAnemia.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicHeartFailure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicObstructivePulmonaryDisease.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicPericardialEffusion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicRenalStenosis.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicVentricularSystolicDysfunction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEConsumeMeal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEImpairedAlveolarExchange.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SELobarPneumonia.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEPatientCondition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEPulmonaryFibrosis.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SESepsis.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArray.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArrayPressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArrayVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArrayVolumePerTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEFunction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEFunctionElectricPotentialVsTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEFunctionVolumeVsTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEHistogram.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEHistogramFractionVsLength.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEProperty.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SERunningAverage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalar0To1.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmount.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmountPerMass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmountPerTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmountPerVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAreaPerTimePressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricCapacitance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricCharge.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricCurrent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricInductance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricPotential.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricResistance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarEnergy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarEnergyPerAmount.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarEnergyPerMass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarForce.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarFrequency.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatCapacitance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatCapacitancePerAmount.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatCapacitancePerMass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatConductance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatConductancePerArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatInductance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatResistance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatResistanceArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarInversePressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarInverseVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarLength.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarLengthPerTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarLengthPerTimePressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerAmount.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerAreaTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerMass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarNegative1To1.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarOsmolality.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarOsmolarity.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPower.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPowerPerAreaTemperatureToTheFourth.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressurePerVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimePerArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimePerVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimePerVolumeArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimeSquaredPerVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarTemperature.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolume.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerPressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimeArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimeMass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimePressure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimePressureArea.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/scenario/SEScenario.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/scenario/SEScenarioExec.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/stdafx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceAerosolization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceClearance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceCompound.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceConcentration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceFraction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstancePharmacodynamics.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstancePharmacokinetics.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstancePhysicochemicals.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceTissuePharmacokinetics.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceTransport.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/SESystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEActiveConditioning.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEAppliedTemperature.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEEnvironment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEEnvironmentalConditions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/actions/SEChangeEnvironmentalConditions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/actions/SEEnvironmentAction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/actions/SEThermalApplication.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/conditions/SEEnvironmentCondition.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/conditions/SEInitialEnvironmentalConditions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/SEAnesthesiaMachine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/SEAnesthesiaMachineChamber.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/SEAnesthesiaMachineOxygenBottle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineAction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineConfiguration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineExpiratoryValveLeak.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineExpiratoryValveObstruction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineInspiratoryValveLeak.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineInspiratoryValveObstruction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineMaskLeak.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineOxygenTankPressureLoss.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineOxygenWallPortPressureLoss.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineSodaLimeFailure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineTubeCuffLeak.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineVaporizerFailure.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineVentilatorPressureLoss.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineYPieceDisconnect.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/electrocardiogram/SEElectroCardioGram.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/electrocardiogram/SEElectroCardioGramWaveform.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/electrocardiogram/SEElectroCardioGramWaveformInterpolator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/inhaler/SEInhaler.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/inhaler/actions/SEInhalerAction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/inhaler/actions/SEInhalerConfiguration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEBloodChemistrySystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SECardiovascularSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEDrugSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEEndocrineSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEEnergySystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEGastrointestinalSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEHepaticSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SENervousSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEPupillaryResponse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SERenalSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SERespiratorySystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SETissueSystem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/ConfigParser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/DataPeak.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/DataTrack.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/EnumHashSpecialization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/FileUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/GeneralMath.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/Logger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/ScopedMutex.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/SmartEnum.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/TimingProfile.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/base64.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/taskrunner/Task.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/taskrunner/TaskProcessor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/taskrunner/TaskQueue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/taskrunner/TaskRunner.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestCase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestErrorStatistics.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestReport.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestSuite.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/CompoundUnit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/CompoundUnitElement.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/PScalar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/PrefixDescriptor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/QuantityConversionDescriptor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/QuantityConversionKey.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/QuantityTypeDescriptor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/SnapValue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UCCommon.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitConversionEngine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitDescriptor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitDimension.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitStringLexer.h
  CPP_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/stdafx.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitCalculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitNode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/SECircuitPath.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuitCalculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuitNode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/electrical/SEElectricalCircuitPath.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuitCalculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuitNode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/fluid/SEFluidCircuitPath.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuitCalculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuitNode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/circuit/thermal/SEThermalCircuitPath.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentGraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentLink.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentNodes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/SECompartmentTransportGraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEFluidCompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEFluidCompartmentLink.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEGasCompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEGasCompartmentGraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SEGasCompartmentLink.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SELiquidCompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SELiquidCompartmentGraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/fluid/SELiquidCompartmentLink.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/substances/SEGasSubstanceQuantity.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/substances/SELiquidSubstanceQuantity.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/substances/SESubstanceQuantity.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/thermal/SEThermalCompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/thermal/SEThermalCompartmentLink.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/compartment/tissue/SETissueCompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEActionManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAdvanceTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAnesthesiaMachineActionCollection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEAutoSerialization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SECondition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEConditionManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDataRequest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDataRequestManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDecimalFormat.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilizationEngineConvergence.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilizationLedger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEDynamicStabilizationPropertyConvergence.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEngineStabilization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEngineTracker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEnvironmentActionCollection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEEventManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEInhalerActionCollection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEPatientActionCollection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SEPatientConfiguration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SESerializeState.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/engine/SETimedStabilization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBActionEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBActions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBAnesthesiaMachine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBAnesthesiaMachineActions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBAnesthesiaMachineEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBCircuit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBCompartment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBCompartmentEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBConditions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBElectroCardioGram.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBElectroCardioGramEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEngine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEngineEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironmentActions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironmentConditions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEnvironmentEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBEvents.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBInhaler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBInhalerActions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatient.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientActionEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientActions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientAssessmentEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientAssessments.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientConditions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPatientNutrition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPhysiology.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPhysiologyEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBProperties.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBScenario.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBSubstance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBSubstanceEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBSubstanceQuantity.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBTestReport.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/SEMeal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/SENutrition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/SEPatient.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAcuteRespiratoryDistressSyndromeExacerbation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAcuteStress.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAirwayObstruction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEAsthmaAttack.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEBrainInjury.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEBronchoconstriction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SECardiacArrest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestCompression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestCompressionForce.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestCompressionForceScale.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChestOcclusiveDressing.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEChronicObstructivePulmonaryDiseaseExacerbation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEConsciousRespiration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEConsciousRespirationCommand.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEConsumeNutrients.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEDyspnea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEExercise.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEForcedExhale.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEForcedInhale.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEForcedPause.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEHemorrhage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEIntubation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SELobarPneumoniaExacerbation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEMechanicalVentilation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SENeedleDecompression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEPatientAction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEPatientAssessmentRequest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEPericardialEffusion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SERespiratoryFatigue.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceAdministration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceBolus.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceCompoundInfusion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESubstanceInfusion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SESupplementalOxygen.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SETensionPneumothorax.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEUrinate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/actions/SEUseInhaler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SECompleteBloodCount.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEComprehensiveMetabolicPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEPatientAssessment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEPulmonaryFunctionTest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEUrinalysis.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/assessments/SEUrinalysisMicroscopic.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEAcuteRespiratoryDistressSyndrome.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicAnemia.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicHeartFailure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicObstructivePulmonaryDisease.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicPericardialEffusion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicRenalStenosis.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEChronicVentricularSystolicDysfunction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEConsumeMeal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEImpairedAlveolarExchange.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SELobarPneumonia.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEPatientCondition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SEPulmonaryFibrosis.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/patient/conditions/SESepsis.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArray.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArrayPressure.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArrayVolume.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEArrayVolumePerTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEFunction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEFunctionElectricPotentialVsTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEFunctionVolumeVsTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEHistogram.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEHistogramFractionVsLength.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEProperty.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SERunningAverage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalar0To1.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmount.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmountPerMass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmountPerTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAmountPerVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarAreaPerTimePressure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricCapacitance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricCharge.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricCurrent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricInductance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricPotential.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarElectricResistance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarEnergy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarEnergyPerAmount.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarEnergyPerMass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarForce.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarFrequency.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatCapacitance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatCapacitancePerAmount.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatCapacitancePerMass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatConductance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatConductancePerArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatInductance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatResistance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarHeatResistanceArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarInversePressure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarInverseVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarLength.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarLengthPerTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarLengthPerTimePressure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerAmount.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerAreaTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerMass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarMassPerVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarNegative1To1.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarOsmolality.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarOsmolarity.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPower.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPowerPerAreaTemperatureToTheFourth.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressurePerVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimePerArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimePerVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimePerVolumeArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarPressureTimeSquaredPerVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarTemperature.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerPressure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimeArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimeMass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimePressure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/properties/SEScalarVolumePerTimePressureArea.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/scenario/SEScenario.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/scenario/SEScenarioExec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/stdafx.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceAerosolization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceClearance.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceCompound.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceConcentration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceFraction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstancePharmacodynamics.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstancePharmacokinetics.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstancePhysicochemicals.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceTissuePharmacokinetics.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/substance/SESubstanceTransport.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/SESystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEActiveConditioning.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEAppliedTemperature.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEEnvironment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/SEEnvironmentalConditions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/actions/SEChangeEnvironmentalConditions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/actions/SEEnvironmentAction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/actions/SEThermalApplication.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/conditions/SEEnvironmentCondition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/environment/conditions/SEInitialEnvironmentalConditions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/SEAnesthesiaMachine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/SEAnesthesiaMachineChamber.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/SEAnesthesiaMachineOxygenBottle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineAction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineConfiguration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineExpiratoryValveLeak.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineExpiratoryValveObstruction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineInspiratoryValveLeak.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineInspiratoryValveObstruction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineMaskLeak.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineOxygenTankPressureLoss.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineOxygenWallPortPressureLoss.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineSodaLimeFailure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineTubeCuffLeak.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineVaporizerFailure.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineVentilatorPressureLoss.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/anesthesiamachine/actions/SEAnesthesiaMachineYPieceDisconnect.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/electrocardiogram/SEElectroCardioGram.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/electrocardiogram/SEElectroCardioGramWaveform.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/electrocardiogram/SEElectroCardioGramWaveformInterpolator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/inhaler/SEInhaler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/inhaler/actions/SEInhalerAction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/equipment/inhaler/actions/SEInhalerConfiguration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEBloodChemistrySystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SECardiovascularSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEDrugSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEEndocrineSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEEnergySystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEGastrointestinalSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEHepaticSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SENervousSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SEPupillaryResponse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SERenalSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SERespiratorySystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/system/physiology/SETissueSystem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/ConfigParser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/DataPeak.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/DataTrack.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/FileUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/GeneralMath.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/Log4cplus.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/Log4cpp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/Logger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/ScopedMutex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/SimpleLogger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/TimingProfile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/base64.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/taskrunner/TaskProcessor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/taskrunner/TaskRunner.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestCase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestErrorStatistics.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestReport.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/testing/SETestSuite.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/CompoundUnit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/CompoundUnitElement.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/PScalar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/PrefixDescriptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/QuantityConversionDescriptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/QuantityConversionKey.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/QuantityTypeDescriptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UCEDefs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitConversionEngine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitDescriptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitDimension.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/utils/unitconversion/UnitStringLexer.cpp
  PUBLIC_DEPENDS
    DataModelBindings
    Dirent
  PRIVATE_DEPENDS
    Eigen3::Eigen
    protobuf::libprotobuf
  GROUP_ROOT
    ${CMAKE_SOURCE_DIR}/cdm/cpp
)
target_include_directories(CommonDataModel PRIVATE ${CMAKE_SOURCE_DIR}/schema/bind/cpp)
target_include_directories(CommonDataModel PRIVATE ${CMAKE_SOURCE_DIR}/schema/bind/cpp/pulse/cdm)