
add_library_ex(PulseEngine
  H_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulseConfiguration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulsePhysiologyEngine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulsePhysiologySystems.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulseScenario.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulseScenarioExec.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/stdafx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Circuits.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Compartments.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Controller.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Engine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/PatientSetup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Substances.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/System.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/environment/Environment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/equipment/AnesthesiaMachine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/equipment/ECG.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/equipment/Inhaler.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/BloodChemistry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Cardiovascular.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Drugs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Endocrine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Energy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Gastrointestinal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Hepatic.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Nervous.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Renal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Respiratory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Saturation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Tissue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulse.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseConfiguration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseEnvironment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseEquipment.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulsePhysiology.h
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseState.h
  CPP_FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulseConfiguration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulsePhysiologyEngine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulseScenario.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/PulseScenarioExec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Circuits.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Compartments.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Controller.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Engine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/PatientSetup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/controller/Substances.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/environment/Environment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/equipment/AnesthesiaMachine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/equipment/ECG.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/equipment/Inhaler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/BloodChemistry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Cardiovascular.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Drugs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Endocrine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Energy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Gastrointestinal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Hepatic.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Nervous.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Renal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Respiratory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Saturation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/physiology/Tissue.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulse.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseEnums.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseConfiguration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseEnvironment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseEquipment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulsePhysiology.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/cpp/io/protobuf/PBPulseState.cpp
  PUBLIC_DEPENDS
    CommonDataModel
  PRIVATE_DEPENDS
    Eigen3::Eigen
    protobuf::libprotobuf
  GROUP_ROOT
    ${CMAKE_SOURCE_DIR}/engine/cpp
)
target_include_directories(PulseEngine PRIVATE ${CMAKE_SOURCE_DIR}/schema/bind/cpp)
target_include_directories(PulseEngine PRIVATE ${CMAKE_SOURCE_DIR}/schema/bind/cpp/pulse/cdm)
target_include_directories(PulseEngine PRIVATE ${CMAKE_SOURCE_DIR}/schema/bind/cpp/pulse/engine)
